# Generated by Django 4.1.4 on 2023-01-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EID', models.IntegerField()),
                ('NAME', models.CharField(max_length=100)),
                ('SAL', models.IntegerField()),
                ('JOB', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
            ],
        ),
    ]
